
/* Drop Tables */

DROP TABLE AD_ADDRESS CASCADE CONSTRAINTS;
DROP TABLE LO_ADMINLOG CASCADE CONSTRAINTS;
DROP TABLE NT_NOTICE CASCADE CONSTRAINTS;
DROP TABLE QU_QUESTION1 CASCADE CONSTRAINTS;
DROP TABLE AD_ADMIN CASCADE CONSTRAINTS;
DROP TABLE AL_COMMENT CASCADE CONSTRAINTS;
DROP TABLE AS_ASSIGN CASCADE CONSTRAINTS;
DROP TABLE VT_VOTE CASCADE CONSTRAINTS;
DROP TABLE CA_CANDIDATES CASCADE CONSTRAINTS;
DROP TABLE DN_DOWNCOUNT CASCADE CONSTRAINTS;
DROP TABLE HT_PLAYCOUNT CASCADE CONSTRAINTS;
DROP TABLE LY_LYLICS CASCADE CONSTRAINTS;
DROP TABLE MY_MYMUSICLIST CASCADE CONSTRAINTS;
DROP TABLE SS_COMMENT CASCADE CONSTRAINTS;
DROP TABLE SS_SOUNDSOURCE CASCADE CONSTRAINTS;
DROP TABLE AL_ALBUM CASCADE CONSTRAINTS;
DROP TABLE MV_COMMENT CASCADE CONSTRAINTS;
DROP TABLE MV_MUSICVIDEO CASCADE CONSTRAINTS;
DROP TABLE TV_COMMENT CASCADE CONSTRAINTS;
DROP TABLE TV_ZAMONGTV CASCADE CONSTRAINTS;
DROP TABLE AT_ARTIST CASCADE CONSTRAINTS;
DROP TABLE ST_STREAMING CASCADE CONSTRAINTS;
DROP TABLE BP_BUYPRODUCT CASCADE CONSTRAINTS;
DROP TABLE QA_QUEASSIGN CASCADE CONSTRAINTS;
DROP TABLE RE_REPLYMQ CASCADE CONSTRAINTS;
DROP TABLE MQ_MYQUESTION CASCADE CONSTRAINTS;
DROP TABLE DV_DIVISION CASCADE CONSTRAINTS;
DROP TABLE GP_ATGROUP CASCADE CONSTRAINTS;
DROP TABLE LK_LIKE CASCADE CONSTRAINTS;
DROP TABLE MA_MUSICAWARD CASCADE CONSTRAINTS;
DROP TABLE MG_COMMENT CASCADE CONSTRAINTS;
DROP TABLE MM_MILIAGE CASCADE CONSTRAINTS;
DROP TABLE ME_MEMBER CASCADE CONSTRAINTS;
DROP TABLE MG_MAGAZINE CASCADE CONSTRAINTS;
DROP TABLE PD_PRODUCT CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE AD_ADDRESS
(
	AD_NO number NOT NULL,
	AD_REGIDATE date DEFAULT SYSDATE NOT NULL,
	ME_NO number NOT NULL,
	AD_ZIP nvarchar2(8) NOT NULL,
	AD_BASIC_ADDR nvarchar2(20) NOT NULL,
	AD_DETAIL_ADDR nvarchar2(30) NOT NULL,
	PRIMARY KEY (AD_NO)
);


CREATE TABLE AD_ADMIN
(
	AD_NO number NOT NULL,
	AD_ID varchar2(10) NOT NULL,
	AD_PASSWORD nvarchar2(20) NOT NULL,
	AD_DEPARTMENT nvarchar2(20) NOT NULL,
	AD_REGIDATE date NOT NULL,
	-- DOMAIN 'S','W','R'
	AD_PERMITLEVEL char(1) NOT NULL,
	PRIMARY KEY (AD_NO)
);


CREATE TABLE AL_ALBUM
(
	AL_NO number NOT NULL,
	AT_NO number NOT NULL,
	AL_ALBUMNAME nvarchar2(50) NOT NULL,
	AL_ARITIST nvarchar2(50) NOT NULL,
	AL_RELEASEDATE date NOT NULL,
	AL_PUBLISHCORP nvarchar2(20) NOT NULL,
	AL_ENTERTAINCORP nvarchar2(20) NOT NULL,
	-- Default 기본사진이미지경로
	AL_ALBUMIMAGE nvarchar2(100) NOT NULL,
	AL_ALBUMINFO varchar2(2000),
	AL_REGIDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (AL_NO)
);


CREATE TABLE AL_COMMENT
(
	AL_CM_NO number NOT NULL,
	AL_CM_REGIDATE date NOT NULL,
	AL_NO number NOT NULL,
	ME_NO number NOT NULL,
	AL_CM_CONTENTS nvarchar2(1000) NOT NULL,
	PRIMARY KEY (AL_CM_NO)
);


CREATE TABLE AS_ASSIGN
(
	AS_NO number NOT NULL,
	AS_REGIDATE date NOT NULL,
	ME_NO number NOT NULL,
	AL_NO number NOT NULL,
	-- DOMAIN "0","1","2","3","4","5"
	AS_GETPOINT char(1) NOT NULL,
	PRIMARY KEY (AS_NO)
);


CREATE TABLE AT_ARTIST
(
	AT_NO number NOT NULL,
	AT_REGIDATE date DEFAULT SYSDATE NOT NULL,
	GP_NO number NOT NULL,
	AT_NAME nvarchar2(30) NOT NULL,
	AT_BELONGGROUP nvarchar2(30) NOT NULL,
	AT_BELONG nvarchar2(20) NOT NULL,
	AT_DEBUTDATE date NOT NULL,
	AT_DEBUTSONG nvarchar2(30) NOT NULL,
	AT_BIRTH date NOT NULL,
	AT_CONTRY nvarchar2(20) NOT NULL,
	-- DOMAIN “M”,”F”
	AT_GENDER char(1) NOT NULL,
	AT_ARTISTINFO nvarchar2(1000) NOT NULL,
	PRIMARY KEY (AT_NO)
);


CREATE TABLE BP_BUYPRODUCT
(
	BP_NO number NOT NULL,
	BP_REGIDATE date DEFAULT SYSDATE NOT NULL,
	PD_NO number NOT NULL,
	ME_NO number NOT NULL,
	BP_PRICE nvarchar2(10) NOT NULL,
	BP_BUYWAY nvarchar2(10) NOT NULL,
	PRIMARY KEY (BP_NO)
);


CREATE TABLE CA_CANDIDATES
(
	CA_NO number NOT NULL,
	CA_REGIDATE date NOT NULL,
	SS_NO number NOT NULL,
	AT_NO number NOT NULL,
	MA_NO number NOT NULL,
	PRIMARY KEY (CA_NO)
);


CREATE TABLE DN_DOWNCOUNT
(
	DN_NO number NOT NULL,
	DN_REGIDATE date NOT NULL,
	ME_NO number NOT NULL,
	SS_NO number NOT NULL,
	PRIMARY KEY (DN_NO)
);


CREATE TABLE DV_DIVISION
(
	DV_NO number NOT NULL,
	DV_DIVISIONCONTENT nvarchar2(50) NOT NULL,
	PRIMARY KEY (DV_NO)
);


CREATE TABLE GP_ATGROUP
(
	GP_NO number NOT NULL,
	GP_REGIDATE date NOT NULL,
	GP_NAME nvarchar2(20) NOT NULL,
	PRIMARY KEY (GP_NO)
);


CREATE TABLE HT_PLAYCOUNT
(
	HT_NO number NOT NULL,
	HT_REGIDATE date NOT NULL,
	ME_NO number NOT NULL,
	SS_NO number NOT NULL,
	PRIMARY KEY (HT_NO)
);


CREATE TABLE LK_LIKE
(
	LK_NO number NOT NULL,
	LK_REGIDATE date NOT NULL,
	ME_NO number NOT NULL,
	LK_FLAG char(6),
	LK_TARGETNO number,
	PRIMARY KEY (LK_NO)
);


CREATE TABLE LO_ADMINLOG
(
	LO_NO number NOT NULL,
	LO_REGIDATE date DEFAULT SYSDATE,
	AD_NO number NOT NULL,
	LO_TARGETTABLE varchar2(5) NOT NULL,
	LO_ACTIONTITLE nvarchar2(10) NOT NULL,
	LO_ACTIONCONTENT nvarchar2(1000),
	PRIMARY KEY (LO_NO)
);


CREATE TABLE LY_LYLICS
(
	LY_NO number NOT NULL,
	LY_CONTENTS nvarchar2(2000) NOT NULL,
	SS_NO number NOT NULL,
	PRIMARY KEY (LY_NO)
);


CREATE TABLE MA_MUSICAWARD
(
	MA_NO number NOT NULL,
	MA_REGIDATE date NOT NULL,
	MA_TITLE nvarchar2(100) NOT NULL,
	MA_CONTENT nvarchar2(1000) NOT NULL,
	-- 종료 전날 23:59:59초까지 집계
	MA_REMAININGDAY date NOT NULL,
	PRIMARY KEY (MA_NO)
);


CREATE TABLE ME_MEMBER
(
	ME_NO number NOT NULL,
	ME_REGIDATE date DEFAULT SYSDATE NOT NULL,
	ME_ID varchar2(20) NOT NULL UNIQUE,
	ME_PASS varchar2(20) NOT NULL,
	ME_NAME nvarchar2(10) NOT NULL,
	ME_NICKNAME nvarchar2(10) NOT NULL UNIQUE,
	-- DOMAIN “M”,”F”
	ME_GENDER char(1) NOT NULL,
	ME_BIRTH char(8) NOT NULL,
	ME_EMAIL varchar2(30) NOT NULL,
	ME_TEL varchar2(13) NOT NULL,
	ME_ADDR nvarchar2(50),
	ME_PHOTO nvarchar2(10) NOT NULL,
	PRIMARY KEY (ME_NO)
);


CREATE TABLE MG_COMMENT
(
	MG_CM_NO number NOT NULL,
	MG_CM_REGIDATE date NOT NULL,
	MG_NO number(10) NOT NULL,
	ME_NO number NOT NULL,
	MG_CM_CONTENTS nvarchar2(1000) NOT NULL,
	PRIMARY KEY (MG_CM_NO)
);


CREATE TABLE MG_MAGAZINE
(
	MG_NO number(10) NOT NULL,
	MG_REGIDATE date NOT NULL,
	MG_TITLE nvarchar2(30) NOT NULL,
	MG_CONTENTS nvarchar2(2000) NOT NULL,
	MG_DIVISION varchar2(20) NOT NULL,
	MG_HITCOUNT number DEFAULT 0,
	PRIMARY KEY (MG_NO)
);


CREATE TABLE MM_MILIAGE
(
	MM_NO number NOT NULL,
	ME_NO number NOT NULL,
	MM_MINUS number(10) DEFAULT 0 NOT NULL,
	PRIMARY KEY (MM_NO)
);


CREATE TABLE MQ_MYQUESTION
(
	MQ_NO number NOT NULL,
	MQ_REGIDATE date NOT NULL,
	DV_NO number NOT NULL,
	ME_NO number NOT NULL,
	MQ_USEENV nvarchar2(15) NOT NULL,
	MQ_OS nvarchar2(10) NOT NULL,
	MQ_BROWSER nvarchar2(8) NOT NULL,
	MQ_USEMODEL nvarchar2(20) NOT NULL,
	MQ_TEL nvarchar2(15) NOT NULL,
	MQ_EMAIL varchar2(30) NOT NULL,
	MQ_TITLE nvarchar2(30) NOT NULL,
	MQ_CONTENTS nvarchar2(2000) NOT NULL,
	-- NULL허용
	MQ_UPLOADFILE varchar2(100) NOT NULL,
	PRIMARY KEY (MQ_NO)
);


CREATE TABLE MV_COMMENT
(
	SS_CM_NO number NOT NULL,
	SS_CM_REGIDATE date NOT NULL,
	MV_NO number NOT NULL,
	ME_NO number NOT NULL,
	SS_CM_CONTENTS nvarchar2(1000) NOT NULL,
	PRIMARY KEY (SS_CM_NO)
);


CREATE TABLE MV_MUSICVIDEO
(
	MV_NO number NOT NULL,
	MV_REGIDATE date NOT NULL,
	AT_NO number NOT NULL,
	MV_TITLE nvarchar2(100),
	MV_CONTENT nvarchar2(1000) NOT NULL,
	MV_LINK varchar2(500) NOT NULL,
	MV_HITCOUNT number DEFAULT 0,
	PRIMARY KEY (MV_NO)
);


CREATE TABLE MY_MYMUSICLIST
(
	MY_NO number NOT NULL,
	MY_REGIDATE date NOT NULL,
	ME_NO number NOT NULL,
	SS_NO number NOT NULL,
	PRIMARY KEY (MY_NO)
);


CREATE TABLE NT_NOTICE
(
	NT_NO number NOT NULL,
	NT_REGIDATE date NOT NULL,
	AD_NO number NOT NULL,
	NT_CLASSIFICATION varchar2(20) NOT NULL,
	NT_TITLE nvarchar2(30) NOT NULL,
	NT_CONTENTS nvarchar2(2000) NOT NULL,
	NT_HITCOUNT number DEFAULT 0 NOT NULL,
	PRIMARY KEY (NT_NO)
);


CREATE TABLE PD_PRODUCT
(
	PD_NO number NOT NULL,
	PD_NAME nvarchar2(10) NOT NULL,
	PD_PRICE number(10),
	PRIMARY KEY (PD_NO)
);


CREATE TABLE QA_QUEASSIGN
(
	QA_NO number NOT NULL,
	QA_REGIDATE date NOT NULL,
	ME_NO number NOT NULL,
	MQ_NO number NOT NULL,
	-- DOMAIN "0","1","2","3","4","5"
	QA_GETPOINT char(1) NOT NULL,
	PRIMARY KEY (QA_NO)
);


CREATE TABLE QU_QUESTION1
(
	QU_NO number NOT NULL,
	QU_REGIDATE date DEFAULT SYSDATE NOT NULL,
	AD_NO number NOT NULL,
	QU_LARGEDIVIDE nvarchar2(20) NOT NULL,
	QU_MEDIUMDIVIDE nvarchar2(20) NOT NULL,
	QU_TITLE nvarchar2(30) NOT NULL,
	QU_CONTENTS nvarchar2(2000) NOT NULL,
	QU_HITCOUNT number NOT NULL,
	QU_LASTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (QU_NO)
);


CREATE TABLE RE_REPLYMQ
(
	RE_MQ_NO number NOT NULL,
	RE_REGIDATE date NOT NULL,
	MQ_NO number NOT NULL,
	RE_TITLE nvarchar2(2000) NOT NULL,
	PRIMARY KEY (RE_MQ_NO)
);


CREATE TABLE SS_COMMENT
(
	SS_CM_NO number NOT NULL,
	SS_CM_REGIDATE date NOT NULL,
	SS_NO number NOT NULL,
	ME_NO number NOT NULL,
	SS_CM_CONTENTS varchar2(20) NOT NULL,
	PRIMARY KEY (SS_CM_NO)
);


CREATE TABLE SS_SOUNDSOURCE
(
	SS_NO number NOT NULL,
	SS_REGIDATE date DEFAULT SYSDATE,
	AL_NO number NOT NULL,
	SS_TITLE nvarchar2(100) NOT NULL,
	SS_GENRE nvarchar2(20) NOT NULL,
	SS_DURATION nvarchar2(10) NOT NULL,
	SS_PATH nvarchar2(200) NOT NULL,
	PRIMARY KEY (SS_NO)
);


CREATE TABLE ST_STREAMING
(
	ST_NO number NOT NULL,
	ST_START_DATE date,
	ST_END_DATE date,
	BP_NO number NOT NULL,
	ME_NO number NOT NULL,
	PRIMARY KEY (ST_NO)
);


CREATE TABLE TV_COMMENT
(
	TV_CM_NO number NOT NULL,
	TV_CM_REGIDATE date NOT NULL,
	TV_NO number NOT NULL,
	ME_NO number NOT NULL,
	TV_CM_CONTENTS nvarchar2(1000) NOT NULL,
	PRIMARY KEY (TV_CM_NO)
);


CREATE TABLE TV_ZAMONGTV
(
	TV_NO number NOT NULL,
	TV_REGIDATE date NOT NULL,
	AT_NO number NOT NULL,
	TV_TITLE nvarchar2(100) NOT NULL,
	TV_CONTENT nvarchar2(1000) NOT NULL,
	TV_LINK varchar2(500) NOT NULL,
	TV_HITCOUNT number DEFAULT 0 NOT NULL,
	PRIMARY KEY (TV_NO)
);


CREATE TABLE VT_VOTE
(
	VT_NO number NOT NULL,
	VT_REGIDATE date NOT NULL,
	ME_NO number NOT NULL,
	CA_NO number NOT NULL,
	PRIMARY KEY (VT_NO)
);



/* Create Foreign Keys */

ALTER TABLE LO_ADMINLOG
	ADD FOREIGN KEY (AD_NO)
	REFERENCES AD_ADMIN (AD_NO)
;


ALTER TABLE NT_NOTICE
	ADD FOREIGN KEY (AD_NO)
	REFERENCES AD_ADMIN (AD_NO)
;


ALTER TABLE QU_QUESTION1
	ADD FOREIGN KEY (AD_NO)
	REFERENCES AD_ADMIN (AD_NO)
;


ALTER TABLE AL_COMMENT
	ADD FOREIGN KEY (AL_NO)
	REFERENCES AL_ALBUM (AL_NO)
;


ALTER TABLE AS_ASSIGN
	ADD FOREIGN KEY (AL_NO)
	REFERENCES AL_ALBUM (AL_NO)
;


ALTER TABLE SS_SOUNDSOURCE
	ADD FOREIGN KEY (AL_NO)
	REFERENCES AL_ALBUM (AL_NO)
;


ALTER TABLE AL_ALBUM
	ADD FOREIGN KEY (AT_NO)
	REFERENCES AT_ARTIST (AT_NO)
;


ALTER TABLE CA_CANDIDATES
	ADD FOREIGN KEY (AT_NO)
	REFERENCES AT_ARTIST (AT_NO)
;


ALTER TABLE MV_MUSICVIDEO
	ADD FOREIGN KEY (AT_NO)
	REFERENCES AT_ARTIST (AT_NO)
;


ALTER TABLE TV_ZAMONGTV
	ADD FOREIGN KEY (AT_NO)
	REFERENCES AT_ARTIST (AT_NO)
;


ALTER TABLE ST_STREAMING
	ADD FOREIGN KEY (BP_NO)
	REFERENCES BP_BUYPRODUCT (BP_NO)
;


ALTER TABLE VT_VOTE
	ADD FOREIGN KEY (CA_NO)
	REFERENCES CA_CANDIDATES (CA_NO)
;


ALTER TABLE MQ_MYQUESTION
	ADD FOREIGN KEY (DV_NO)
	REFERENCES DV_DIVISION (DV_NO)
;


ALTER TABLE AT_ARTIST
	ADD FOREIGN KEY (GP_NO)
	REFERENCES GP_ATGROUP (GP_NO)
;


ALTER TABLE CA_CANDIDATES
	ADD FOREIGN KEY (MA_NO)
	REFERENCES MA_MUSICAWARD (MA_NO)
;


ALTER TABLE AD_ADDRESS
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE AL_COMMENT
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE AS_ASSIGN
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE BP_BUYPRODUCT
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE DN_DOWNCOUNT
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE HT_PLAYCOUNT
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE LK_LIKE
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE MG_COMMENT
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE MM_MILIAGE
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE MQ_MYQUESTION
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE MV_COMMENT
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE MY_MYMUSICLIST
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE QA_QUEASSIGN
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE SS_COMMENT
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE ST_STREAMING
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE TV_COMMENT
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE VT_VOTE
	ADD FOREIGN KEY (ME_NO)
	REFERENCES ME_MEMBER (ME_NO)
;


ALTER TABLE MG_COMMENT
	ADD FOREIGN KEY (MG_NO)
	REFERENCES MG_MAGAZINE (MG_NO)
;


ALTER TABLE QA_QUEASSIGN
	ADD FOREIGN KEY (MQ_NO)
	REFERENCES MQ_MYQUESTION (MQ_NO)
;


ALTER TABLE RE_REPLYMQ
	ADD FOREIGN KEY (MQ_NO)
	REFERENCES MQ_MYQUESTION (MQ_NO)
;


ALTER TABLE MV_COMMENT
	ADD FOREIGN KEY (MV_NO)
	REFERENCES MV_MUSICVIDEO (MV_NO)
;


ALTER TABLE BP_BUYPRODUCT
	ADD FOREIGN KEY (PD_NO)
	REFERENCES PD_PRODUCT (PD_NO)
;


ALTER TABLE CA_CANDIDATES
	ADD FOREIGN KEY (SS_NO)
	REFERENCES SS_SOUNDSOURCE (SS_NO)
;


ALTER TABLE DN_DOWNCOUNT
	ADD FOREIGN KEY (SS_NO)
	REFERENCES SS_SOUNDSOURCE (SS_NO)
;


ALTER TABLE HT_PLAYCOUNT
	ADD FOREIGN KEY (SS_NO)
	REFERENCES SS_SOUNDSOURCE (SS_NO)
;


ALTER TABLE LY_LYLICS
	ADD FOREIGN KEY (SS_NO)
	REFERENCES SS_SOUNDSOURCE (SS_NO)
;


ALTER TABLE MY_MYMUSICLIST
	ADD FOREIGN KEY (SS_NO)
	REFERENCES SS_SOUNDSOURCE (SS_NO)
;


ALTER TABLE SS_COMMENT
	ADD FOREIGN KEY (SS_NO)
	REFERENCES SS_SOUNDSOURCE (SS_NO)
;


ALTER TABLE TV_COMMENT
	ADD FOREIGN KEY (TV_NO)
	REFERENCES TV_ZAMONGTV (TV_NO)
;



/* Comments */

COMMENT ON COLUMN AD_ADMIN.AD_PERMITLEVEL IS 'DOMAIN ''S'',''W'',''R''';
COMMENT ON COLUMN AL_ALBUM.AL_ALBUMIMAGE IS 'Default 기본사진이미지경로';
COMMENT ON COLUMN AS_ASSIGN.AS_GETPOINT IS 'DOMAIN "0","1","2","3","4","5"';
COMMENT ON COLUMN AT_ARTIST.AT_GENDER IS 'DOMAIN “M”,”F”';
COMMENT ON COLUMN MA_MUSICAWARD.MA_REMAININGDAY IS '종료 전날 23:59:59초까지 집계';
COMMENT ON COLUMN ME_MEMBER.ME_GENDER IS 'DOMAIN “M”,”F”';
COMMENT ON COLUMN MQ_MYQUESTION.MQ_UPLOADFILE IS 'NULL허용';
COMMENT ON COLUMN QA_QUEASSIGN.QA_GETPOINT IS 'DOMAIN "0","1","2","3","4","5"';



